import type { StaticTrackDefinition } from "../types";

export const leetcodeContent: StaticTrackDefinition = {
  id: "leetcode",
  label: "LeetCode",
  summary: "Keep core problem-solving patterns warm with steady repetition.",
  accent: "peach",
  groups: [
    {
      id: "arrays-hashing",
      title: "Array",
      items: [
        { id: "contains-duplicate", title: "Contains Duplicate" },
        { id: "valid-anagram", title: "Valid Anagram" },
        { id: "two-sum", title: "Two Sum" },
        { id: "group-anagrams", title: "Group Anagrams" },
        { id: "top-k-frequent-elements", title: "Top K Frequent Elements" },
        { id: "product-of-array-except-self", title: "Product of Array Except Self" },
        { id: "valid-sudoku", title: "Valid Sudoku" },
        { id: "encode-and-decode-strings", title: "Encode and Decode Strings" },
        { id: "longest-consecutive-sequence", title: "Longest Consecutive Sequence" },
      ],
    },
    {
      id: "two-pointers",
      title: "Two Pointers",
      items: [
        { id: "valid-palindrome", title: "Valid Palindrome" },
        { id: "two-sum-ii-input-array-is-sorted", title: "Sorted Input 2Sum" },
        { id: "three-sum", title: "3 Sum" },
        { id: "container-with-most-water", title: "Container With Most Water" },
        { id: "trapping-rain-water", title: "Trapping Rain Water" },
      ],
    },
    {
      id: "sliding-window",
      title: "Sliding Window",
      items: [
        { id: "best-time-to-buy-and-sell-stock", title: "Best Time to Buy And Sell Stock" },
        { id: "longest-substring-without-repeating-characters", title: "Longest Substring Without Repeating Characters" },
        { id: "longest-repeating-character-replacement", title: "Longest Repeating Character Replacement" },
        { id: "permutation-in-string", title: "Permutation In String" },
        { id: "minimum-window-substring", title: "Minimum Window Substring" },
        { id: "sliding-window-maximum", title: "Sliding Window Maximum" },
      ],
    },
    {
      id: "stack",
      title: "Stack",
      items: [
        { id: "valid-parentheses", title: "Valid Parentheses" },
        { id: "min-stack", title: "Min Stack" },
        { id: "evaluate-reverse-polish-notation", title: "Evaluate Reverse Polish Notation" },
        { id: "generate-parentheses", title: "Generate Parentheses" },
        { id: "daily-temperatures", title: "Daily Temperatures" },
        { id: "largest-rectangle-in-histogram", title: "Largest Rectangle In Histogram" },
      ],
    },
    {
      id: "binary-search",
      title: "Binary Search",
      items: [
        { id: "binary-search", title: "Binary Search" },
        { id: "search-a-2d-matrix", title: "Search a 2D Matrix" },
        { id: "koko-eating-bananas", title: "Koko Eating Bananas" },
        { id: "find-minimum-in-rotated-sorted-array", title: "Find Minimum In Rotated Sorted Array" },
        { id: "search-in-rotated-sorted-array", title: "Search In Rotated Sorted Array" },
        { id: "time-based-key-value-store", title: "Time Based Key-Value Store" },
        { id: "median-of-two-sorted-arrays", title: "Median of Two Sorted Arrays" },
      ],
    },
    {
      id: "linked-list",
      title: "Linked List",
      items: [
        { id: "reverse-linked-list", title: "Reverse Linked List" },
        { id: "merge-two-sorted-lists", title: "Merge Two Sorted Lists" },
        { id: "reorder-list", title: "Reorder List" },
        { id: "remove-nth-node-from-end-of-list", title: "Remove Nth Node From End of List" },
        { id: "copy-list-with-random-pointer", title: "Copy List With Random Pointer" },
        { id: "add-two-numbers", title: "Add Two Numbers" },
        { id: "linked-list-cycle", title: "Linked List Cycle" },
        { id: "find-the-duplicate-number", title: "Find The Duplicate Number" },
        { id: "lru-cache", title: "LRU Cache" },
        { id: "merge-k-sorted-lists", title: "Merge K Sorted Lists" },
        { id: "reverse-nodes-in-k-group", title: "Reverse Nodes In K-Group" },
      ],
    },
    {
      id: "trees",
      title: "Trees",
      items: [
        { id: "invert-binary-tree", title: "Invert Binary Tree" },
        { id: "maximum-depth-of-binary-tree", title: "Maximum Depth of Binary Tree" },
        { id: "diameter-of-binary-tree", title: "Diameter of Binary Tree" },
        { id: "balanced-binary-tree", title: "Balanced Binary Tree" },
        { id: "same-tree", title: "Same Tree" },
        { id: "subtree-of-another-tree", title: "Subtree of Another Tree" },
        { id: "lowest-common-ancestor-of-a-binary-search-tree", title: "Lowest Common Ancestor of a Binary Search Tree" },
        { id: "binary-tree-level-order-traversal", title: "Binary Tree Level Order Traversal" },
        { id: "binary-tree-right-side-view", title: "Binary Tree Right Side View" },
        { id: "count-good-nodes-in-binary-tree", title: "Count Good Nodes in Binary Tree" },
        { id: "validate-binary-search-tree", title: "Validate Binary Search Tree" },
        { id: "kth-smallest-element-in-a-bst", title: "Kth Smallest Element in a BST" },
        { id: "construct-binary-tree-from-preorder-and-inorder-traversal", title: "Construct Binary Tree from Preorder and Inorder Traversal" },
        { id: "binary-tree-maximum-path-sum", title: "Binary Tree Maximum Path Sum" },
        { id: "serialize-and-deserialize-binary-tree", title: "Serialize and Deserialize Binary Tree" },
      ],
    },
    {
      id: "heap-priority-queue",
      title: "Heap",
      items: [
        { id: "kth-largest-element-in-a-stream", title: "Kth Largest Element in a Stream" },
        { id: "last-stone-weight", title: "Last Stone Weight" },
        { id: "k-closest-points-to-origin", title: "K Closest Points to Origin" },
        { id: "kth-largest-element-in-an-array", title: "Kth Largest Element in an Array" },
        { id: "task-scheduler", title: "Task Scheduler" },
        { id: "design-twitter", title: "Design Twitter" },
        { id: "find-median-from-data-stream", title: "Find Median from Data Stream" },
      ],
    },
    {
      id: "backtracking",
      title: "Backtrack",
      items: [
        { id: "subsets", title: "Subsets" },
        { id: "combination-sum", title: "Combination Sum" },
        { id: "permutations", title: "Permutations" },
        { id: "subsets-ii", title: "Subsets II" },
        { id: "combination-sum-ii", title: "Combination Sum II" },
        { id: "word-search", title: "Word Search" },
        { id: "palindrome-partitioning", title: "Palindrome Partitioning" },
        { id: "letter-combinations-of-a-phone-number", title: "Letter Combinations of a Phone Number" },
        { id: "n-queens", title: "N-Queens" },
        { id: "matchsticks-to-square", title: "Matchsticks to Square" },
      ],
    },
    {
      id: "tries",
      title: "Trie",
      items: [
        { id: "implement-trie-prefix-tree", title: "Implement Trie (Prefix Tree)" },
        { id: "design-add-and-search-words-data-structure", title: "Design Add and Search Words Data Structure" },
        { id: "word-search-ii", title: "Word Search II" },
      ],
    },
    {
      id: "graphs",
      title: "Graphs I",
      items: [
        { id: "number-of-islands", title: "Number of Islands" },
        { id: "clone-graph", title: "Clone Graph" },
        { id: "max-area-of-island", title: "Max Area of Island" },
        { id: "pacific-atlantic-water-flow", title: "Pacific Atlantic Water Flow" },
        { id: "surrounded-regions", title: "Surrounded Regions" },
        { id: "rotting-oranges", title: "Rotting Oranges" },
        { id: "walls-and-gates", title: "Walls and Gates" },
        { id: "course-schedule", title: "Course Schedule" },
        { id: "course-schedule-ii", title: "Course Schedule II" },
        { id: "redundant-connection", title: "Redundant Connection" },
        { id: "number-of-connected-components-in-an-undirected-graph", title: "Number of Connected Components in an Undirected Graph" },
        { id: "graph-valid-tree", title: "Graph Valid Tree" },
        { id: "word-ladder", title: "Word Ladder" },
      ],
    },
    {
      id: "advanced-graphs",
      title: "Graphs II",
      items: [
        { id: "reconstruct-itinerary", title: "Reconstruct Itinerary" },
        { id: "min-cost-to-connect-all-points", title: "Min Cost to Connect All Points" },
        { id: "network-delay-time", title: "Network Delay Time" },
        { id: "swim-in-rising-water", title: "Swim in Rising Water" },
        { id: "alien-dictionary", title: "Alien Dictionary" },
        { id: "cheapest-flights-within-k-stops", title: "Cheapest Flights Within K Stops" },
      ],
    },
    {
      id: "1d-dynamic-programming",
      title: "1D Dynamic Programming",
      items: [
        { id: "climbing-stairs", title: "Climbing Stairs" },
        { id: "min-cost-climbing-stairs", title: "Min Cost Climbing Stairs" },
        { id: "house-robber", title: "House Robber" },
        { id: "house-robber-ii", title: "House Robber II" },
        { id: "longest-palindromic-substring", title: "Longest Palindromic Substring" },
        { id: "palindromic-substrings", title: "Palindromic Substrings" },
        { id: "decode-ways", title: "Decode Ways" },
        { id: "coin-change", title: "Coin Change" },
        { id: "maximum-product-subarray", title: "Maximum Product Subarray" },
        { id: "word-break", title: "Word Break" },
        { id: "longest-increasing-subsequence", title: "Longest Increasing Subsequence" },
        { id: "partition-equal-subset-sum", title: "Partition Equal Subset Sum" },
      ],
    },
    {
      id: "2d-dynamic-programming",
      title: "2D Dynamic Programming",
      items: [
        { id: "unique-paths", title: "Unique Paths" },
        { id: "longest-common-subsequence", title: "Longest Common Subsequence" },
        { id: "best-time-to-buy-and-sell-stock-with-cooldown", title: "Best Time to Buy And Sell Stock With Cooldown" },
        { id: "coin-change-ii", title: "Coin Change II" },
        { id: "target-sum", title: "Target Sum" },
        { id: "interleaving-string", title: "Interleaving String" },
        { id: "longest-increasing-path-in-a-matrix", title: "Longest Increasing Path in a Matrix" },
        { id: "distinct-subsequences", title: "Distinct Subsequences" },
        { id: "edit-distance", title: "Edit Distance" },
        { id: "burst-balloons", title: "Burst Balloons" },
        { id: "regular-expression-matching", title: "Regular Expression Matching" },
      ],
    },
    {
      id: "greedy",
      title: "Greedy",
      items: [
        { id: "maximum-subarray", title: "Maximum Subarray" },
        { id: "jump-game", title: "Jump Game" },
        { id: "jump-game-ii", title: "Jump Game II" },
        { id: "gas-station", title: "Gas Station" },
        { id: "hand-of-straights", title: "Hand of Straights" },
        { id: "merge-triplets-to-form-target-triplet", title: "Merge Triplets to Form Target Triplet" },
        { id: "partition-labels", title: "Partition Labels" },
        { id: "valid-parenthesis-string", title: "Valid Parenthesis String" },
      ],
    },
    {
      id: "intervals",
      title: "Intervals",
      items: [
        { id: "insert-interval", title: "Insert Interval" },
        { id: "merge-intervals", title: "Merge Intervals" },
        { id: "non-overlapping-intervals", title: "Non-overlapping Intervals" },
        { id: "meeting-rooms", title: "Meeting Rooms" },
        { id: "meeting-rooms-ii", title: "Meeting Rooms II" },
        { id: "minimum-interval-to-include-each-query", title: "Minimum Interval to Include Each Query" },
      ],
    },
    {
      id: "math-and-geometry",
      title: "Math and Geometry",
      items: [
        { id: "rotate-image", title: "Rotate Image" },
        { id: "spiral-matrix", title: "Spiral Matrix" },
        { id: "set-matrix-zeroes", title: "Set Matrix Zeroes" },
        { id: "happy-number", title: "Happy Number" },
        { id: "plus-one", title: "Plus One" },
        { id: "pow-x-n", title: "Pow(x, n)" },
        { id: "multiply-strings", title: "Multiply Strings" },
        { id: "detect-squares", title: "Detect Squares" },
      ],
    },
    {
      id: "bit-manipulation",
      title: "Bits",
      items: [
        { id: "single-number", title: "Single Number" },
        { id: "number-of-1-bits", title: "Number of 1 Bits" },
        { id: "counting-bits", title: "Counting Bits" },
        { id: "reverse-bits", title: "Reverse Bits" },
        { id: "missing-number", title: "Missing Number" },
        { id: "sum-of-two-integers", title: "Sum of Two Integers" },
        { id: "bitwise-and-of-numbers-range", title: "Bitwise AND of Numbers Range" },
      ],
    },
  ],
};
