import type { StaticTrackDefinition } from "../types";

export const leetcodeContent: StaticTrackDefinition = {
  id: "leetcode",
  label: "LeetCode",
  summary: "Keep core problem-solving patterns warm with steady repetition.",
  accent: "peach",
  groups: [
    {
      id: "arrays-hashing",
      title: "Array",
      items: [
        { id: "contains-duplicate", title: "Contains Duplicate", difficulty: "easy" },
        { id: "valid-anagram", title: "Valid Anagram", difficulty: "easy" },
        { id: "two-sum", title: "Two Sum", difficulty: "easy" },
        { id: "group-anagrams", title: "Group Anagrams", difficulty: "medium" },
        { id: "top-k-frequent-elements", title: "Top K Frequent Elements", difficulty: "medium" },
        { id: "product-of-array-except-self", title: "Product of Array Except Self", difficulty: "medium" },
        { id: "valid-sudoku", title: "Valid Sudoku", difficulty: "medium" },
        { id: "encode-and-decode-strings", title: "Encode and Decode Strings", difficulty: "medium" },
        { id: "longest-consecutive-sequence", title: "Longest Consecutive Sequence", difficulty: "medium" },
      ],
    },
    {
      id: "two-pointers",
      title: "Two Pointers",
      items: [
        { id: "valid-palindrome", title: "Valid Palindrome", difficulty: "easy" },
        { id: "two-sum-ii-input-array-is-sorted", title: "Sorted Input 2Sum", difficulty: "medium" },
        { id: "three-sum", title: "3 Sum", difficulty: "medium" },
        { id: "container-with-most-water", title: "Container With Most Water", difficulty: "medium" },
        { id: "trapping-rain-water", title: "Trapping Rain Water", difficulty: "hard" },
      ],
    },
    {
      id: "sliding-window",
      title: "Sliding Window",
      items: [
        { id: "best-time-to-buy-and-sell-stock", title: "Best Time to Buy And Sell Stock", difficulty: "easy" },
        { id: "longest-substring-without-repeating-characters", title: "Longest Substring Without Repeating Characters", difficulty: "medium" },
        { id: "longest-repeating-character-replacement", title: "Longest Repeating Character Replacement", difficulty: "medium" },
        { id: "permutation-in-string", title: "Permutation In String", difficulty: "medium" },
        { id: "minimum-window-substring", title: "Minimum Window Substring", difficulty: "hard" },
        { id: "sliding-window-maximum", title: "Sliding Window Maximum", difficulty: "hard" },
      ],
    },
    {
      id: "stack",
      title: "Stack",
      items: [
        { id: "valid-parentheses", title: "Valid Parentheses", difficulty: "easy" },
        { id: "min-stack", title: "Min Stack", difficulty: "medium" },
        { id: "evaluate-reverse-polish-notation", title: "Evaluate Reverse Polish Notation", difficulty: "medium" },
        { id: "car-fleet", title: "Car Fleet", difficulty: "medium" },
        { id: "daily-temperatures", title: "Daily Temperatures", difficulty: "medium" },
        { id: "largest-rectangle-in-histogram", title: "Largest Rectangle In Histogram", difficulty: "hard" },
      ],
    },
    {
      id: "binary-search",
      title: "Binary Search",
      items: [
        { id: "binary-search", title: "Binary Search", difficulty: "easy" },
        { id: "search-a-2d-matrix", title: "Search a 2D Matrix", difficulty: "medium" },
        { id: "koko-eating-bananas", title: "Koko Eating Bananas", difficulty: "medium" },
        { id: "find-minimum-in-rotated-sorted-array", title: "Find Minimum In Rotated Sorted Array", difficulty: "medium" },
        { id: "search-in-rotated-sorted-array", title: "Search In Rotated Sorted Array", difficulty: "medium" },
        { id: "time-based-key-value-store", title: "Time Based Key-Value Store", difficulty: "medium" },
        { id: "median-of-two-sorted-arrays", title: "Median of Two Sorted Arrays", difficulty: "hard" },
      ],
    },
    {
      id: "linked-list",
      title: "Linked List",
      items: [
        { id: "reverse-linked-list", title: "Reverse Linked List", difficulty: "easy" },
        { id: "merge-two-sorted-lists", title: "Merge Two Sorted Lists", difficulty: "easy" },
        { id: "reorder-list", title: "Reorder List", difficulty: "medium" },
        { id: "remove-nth-node-from-end-of-list", title: "Remove Nth Node From End of List", difficulty: "medium" },
        { id: "copy-list-with-random-pointer", title: "Copy List With Random Pointer", difficulty: "medium" },
        { id: "add-two-numbers", title: "Add Two Numbers", difficulty: "medium" },
        { id: "linked-list-cycle", title: "Linked List Cycle", difficulty: "easy" },
        { id: "find-the-duplicate-number", title: "Find The Duplicate Number", difficulty: "medium" },
        { id: "lru-cache", title: "LRU Cache", difficulty: "medium" },
        { id: "merge-k-sorted-lists", title: "Merge K Sorted Lists", difficulty: "hard" },
        { id: "reverse-nodes-in-k-group", title: "Reverse Nodes In K-Group", difficulty: "hard" },
      ],
    },
    {
      id: "trees",
      title: "Trees",
      items: [
        { id: "invert-binary-tree", title: "Invert Binary Tree", difficulty: "easy" },
        { id: "maximum-depth-of-binary-tree", title: "Maximum Depth of Binary Tree", difficulty: "easy" },
        { id: "diameter-of-binary-tree", title: "Diameter of Binary Tree", difficulty: "easy" },
        { id: "balanced-binary-tree", title: "Balanced Binary Tree", difficulty: "easy" },
        { id: "same-tree", title: "Is Same Tree", difficulty: "easy" },
        { id: "subtree-of-another-tree", title: "Subtree of Another Tree", difficulty: "easy", linkTitle: "Is SubTree" },
        {
          id: "lowest-common-ancestor-of-a-binary-search-tree",
          title: "Lowest Common Ancestor of a Binary Search Tree",
          difficulty: "medium",
          linkTitle: "Lowest Common Ancestor BST",
        },
        { id: "binary-tree-level-order-traversal", title: "Binary Tree Level Order Traversal", difficulty: "medium", linkTitle: "Level Order Traversal" },
        { id: "binary-tree-right-side-view", title: "Binary Tree Right Side View", difficulty: "medium", linkTitle: "Right Side Tree View" },
        { id: "count-good-nodes-in-binary-tree", title: "Count Good Nodes in Binary Tree", difficulty: "medium", linkTitle: "Count Good Nodes" },
        { id: "validate-binary-search-tree", title: "Validate Binary Search Tree", difficulty: "medium" },
        { id: "kth-smallest-element-in-a-bst", title: "Kth Smallest Element in a BST", difficulty: "medium", linkTitle: "Kth Smallest Element in BST" },
        { id: "construct-binary-tree-from-preorder-and-inorder-traversal", title: "Construct Binary Tree from Preorder and Inorder Traversal", difficulty: "medium", linkTitle: "Construct Tree From Traversals" },
        { id: "binary-tree-maximum-path-sum", title: "Binary Tree Maximum Path Sum", difficulty: "hard" },
        { id: "serialize-and-deserialize-binary-tree", title: "Serialize and Deserialize Binary Tree", difficulty: "hard" },
      ],
    },
    {
      id: "heap-priority-queue",
      title: "Heap",
      items: [
        { id: "kth-largest-element-in-a-stream", title: "Kth Largest Element in a Stream", difficulty: "easy" },
        { id: "last-stone-weight", title: "Last Stone Weight", difficulty: "easy" },
        { id: "k-closest-points-to-origin", title: "K Closest Points to Origin", difficulty: "medium" },
        { id: "kth-largest-element-in-an-array", title: "Kth Largest Element in an Array", difficulty: "medium" },
        { id: "task-scheduler", title: "Task Scheduler", difficulty: "medium" },
        { id: "design-twitter", title: "Design Twitter", difficulty: "medium" },
        { id: "find-median-from-data-stream", title: "Find Median from Data Stream", difficulty: "hard" },
      ],
    },
    {
      id: "backtracking",
      title: "Backtrack",
      items: [
        { id: "subsets", title: "Subsets", difficulty: "medium" },
        { id: "combination-sum", title: "Combination Sum", difficulty: "medium" },
        { id: "permutations", title: "Permutations", difficulty: "medium" },
        { id: "subsets-ii", title: "Subsets II", difficulty: "medium" },
        { id: "combination-sum-ii", title: "Combination Sum II", difficulty: "medium" },
        { id: "word-search", title: "Word Search", difficulty: "medium" },
        { id: "palindrome-partitioning", title: "Palindrome Partitioning", difficulty: "medium" },
        { id: "letter-combinations-of-a-phone-number", title: "Letter Combinations of a Phone Number", difficulty: "medium" },
        { id: "n-queens", title: "N-Queens", difficulty: "hard" },
        { id: "generate-parentheses", title: "Generate Parentheses", difficulty: "medium", linkTitle: "Generate Parentheses" }
      ],
    },
    {
      id: "tries",
      title: "Trie",
      items: [
        { id: "implement-trie-prefix-tree", title: "Implement Trie (Prefix Tree)", difficulty: "medium" },
        { id: "design-add-and-search-words-data-structure", title: "Design Add and Search Words Data Structure", difficulty: "medium" },
        { id: "word-search-ii", title: "Word Search II", difficulty: "hard" },
      ],
    },
    {
      id: "graphs",
      title: "Graphs I",
      linkTitle: "Graph",
      items: [
        { id: "number-of-islands", title: "Number of Islands", difficulty: "medium" },
        { id: "clone-graph", title: "Clone Graph", difficulty: "medium" },
        { id: "max-area-of-island", title: "Max Area of Island", difficulty: "medium" },
        { id: "pacific-atlantic-water-flow", title: "Pacific Atlantic Water Flow", difficulty: "medium" },
        { id: "surrounded-regions", title: "Surrounded Regions", difficulty: "medium" },
        { id: "rotting-oranges", title: "Rotting Oranges", difficulty: "medium" },
        { id: "walls-and-gates", title: "Walls and Gates", difficulty: "medium" },
        { id: "course-schedule", title: "Course Schedule", difficulty: "medium" },
        { id: "course-schedule-ii", title: "Course Schedule II", difficulty: "medium" },
        { id: "redundant-connection", title: "Redundant Connection", difficulty: "medium" },
        { id: "number-of-connected-components-in-an-undirected-graph", title: "Number of Connected Components in an Undirected Graph", difficulty: "medium" },
        { id: "graph-valid-tree", title: "Graph Valid Tree", difficulty: "medium" },
        { id: "word-ladder", title: "Word Ladder", difficulty: "hard" },
      ],
    },
    {
      id: "advanced-graphs",
      title: "Graphs II",
      linkTitle: "Graph",
      items: [
        { id: "reconstruct-itinerary", title: "Reconstruct Itinerary", difficulty: "hard" },
        { id: "min-cost-to-connect-all-points", title: "Min Cost to Connect All Points", difficulty: "medium" },
        { id: "network-delay-time", title: "Network Delay Time", difficulty: "medium" },
        { id: "swim-in-rising-water", title: "Swim in Rising Water", difficulty: "hard" },
        { id: "alien-dictionary", title: "Alien Dictionary", difficulty: "hard" },
        { id: "cheapest-flights-within-k-stops", title: "Cheapest Flights Within K Stops", difficulty: "medium" },
      ],
    },
    {
      id: "1d-dynamic-programming",
      title: "1D dp",
      linkTitle: "Dynamic Programming",
      items: [
        { id: "climbing-stairs", title: "Climbing Stairs", difficulty: "easy" },
        { id: "min-cost-climbing-stairs", title: "Min Cost Climbing Stairs", difficulty: "easy" },
        { id: "house-robber", title: "House Robber", difficulty: "medium" },
        { id: "house-robber-ii", title: "House Robber II", difficulty: "medium" },
        { id: "longest-palindromic-substring", title: "Longest Palindromic Substring", difficulty: "medium" },
        { id: "palindromic-substrings", title: "Palindromic Substrings", difficulty: "medium" },
        { id: "decode-ways", title: "Decode Ways", difficulty: "medium" },
        { id: "coin-change", title: "Coin Change", difficulty: "medium" },
        { id: "maximum-product-subarray", title: "Maximum Product Subarray", difficulty: "medium" },
        { id: "word-break", title: "Word Break", difficulty: "medium" },
        { id: "longest-increasing-subsequence", title: "Longest Increasing Subsequence", difficulty: "medium" },
        { id: "partition-equal-subset-sum", title: "Partition Equal Subset Sum", difficulty: "medium" },
      ],
    },
    {
      id: "2d-dynamic-programming",
      title: "2D dp",
      linkTitle: "Dynamic Programming",
      items: [
        { id: "unique-paths", title: "Unique Paths", difficulty: "medium" },
        { id: "longest-common-subsequence", title: "Longest Common Subsequence", difficulty: "medium" },
        { id: "best-time-to-buy-and-sell-stock-with-cooldown", title: "Best Time to Buy And Sell Stock With Cooldown", difficulty: "medium" },
        { id: "coin-change-ii", title: "Coin Change II", difficulty: "medium" },
        { id: "target-sum", title: "Target Sum", difficulty: "medium" },
        { id: "interleaving-string", title: "Interleaving String", difficulty: "medium" },
        { id: "longest-increasing-path-in-a-matrix", title: "Longest Increasing Path in a Matrix", difficulty: "hard" },
        { id: "distinct-subsequences", title: "Distinct Subsequences", difficulty: "hard" },
        { id: "edit-distance", title: "Edit Distance", difficulty: "medium" },
        { id: "burst-balloons", title: "Burst Balloons", difficulty: "hard" },
        { id: "regular-expression-matching", title: "Regular Expression Matching", difficulty: "hard" },
      ],
    },
    {
      id: "greedy",
      title: "Greedy",
      items: [
        { id: "maximum-subarray", title: "Maximum Subarray", difficulty: "medium" },
        { id: "jump-game", title: "Jump Game", difficulty: "medium" },
        { id: "jump-game-ii", title: "Jump Game II", difficulty: "medium" },
        { id: "gas-station", title: "Gas Station", difficulty: "medium" },
        { id: "hand-of-straights", title: "Hand of Straights", difficulty: "medium" },
        { id: "merge-triplets-to-form-target-triplet", title: "Merge Triplets to Form Target Triplet", difficulty: "medium" },
        { id: "partition-labels", title: "Partition Labels", difficulty: "medium" },
        { id: "valid-parenthesis-string", title: "Valid Parenthesis String", difficulty: "medium" },
      ],
    },
    {
      id: "intervals",
      title: "Intervals",
      items: [
        { id: "insert-interval", title: "Insert Interval", difficulty: "medium" },
        { id: "merge-intervals", title: "Merge Intervals", difficulty: "medium" },
        { id: "non-overlapping-intervals", title: "Non-overlapping Intervals", difficulty: "medium" },
        { id: "meeting-rooms", title: "Meeting Rooms", difficulty: "easy" },
        { id: "meeting-rooms-ii", title: "Meeting Rooms II", difficulty: "medium" },
        { id: "minimum-interval-to-include-each-query", title: "Minimum Interval to Include Each Query", difficulty: "hard" },
      ],
    },
    {
      id: "math-and-geometry",
      title: "Math and Geometry",
      items: [
        { id: "rotate-image", title: "Rotate Image", difficulty: "medium" },
        { id: "spiral-matrix", title: "Spiral Matrix", difficulty: "medium" },
        { id: "set-matrix-zeroes", title: "Set Matrix Zeroes", difficulty: "medium" },
        { id: "happy-number", title: "Happy Number", difficulty: "easy" },
        { id: "plus-one", title: "Plus One", difficulty: "easy" },
        { id: "pow-x-n", title: "Pow(x, n)", difficulty: "medium" },
        { id: "multiply-strings", title: "Multiply Strings", difficulty: "medium" },
        { id: "detect-squares", title: "Detect Squares", difficulty: "medium" },
      ],
    },
    {
      id: "bit-manipulation",
      title: "Bits",
      items: [
        { id: "single-number", title: "Single Number", difficulty: "easy" },
        { id: "number-of-1-bits", title: "Number of 1 Bits", difficulty: "easy" },
        { id: "counting-bits", title: "Counting Bits", difficulty: "easy" },
        { id: "reverse-bits", title: "Reverse Bits", difficulty: "easy" },
        { id: "missing-number", title: "Missing Number", difficulty: "easy" },
        { id: "sum-of-two-integers", title: "Sum of Two Integers", difficulty: "medium" },
        { id: "bitwise-and-of-numbers-range", title: "Bitwise AND of Numbers Range", difficulty: "medium" },
      ],
    },
  ],
};
